// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: dex.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ── GetPokemon ──────────────────────────────────────────────
type GetPokemonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PokemonId     int32                  `protobuf:"varint,1,opt,name=pokemon_id,json=pokemonId,proto3" json:"pokemon_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPokemonRequest) Reset() {
	*x = GetPokemonRequest{}
	mi := &file_dex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPokemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPokemonRequest) ProtoMessage() {}

func (x *GetPokemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPokemonRequest.ProtoReflect.Descriptor instead.
func (*GetPokemonRequest) Descriptor() ([]byte, []int) {
	return file_dex_proto_rawDescGZIP(), []int{0}
}

func (x *GetPokemonRequest) GetPokemonId() int32 {
	if x != nil {
		return x.PokemonId
	}
	return 0
}

type PokemonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PokemonId     int32                  `protobuf:"varint,1,opt,name=pokemon_id,json=pokemonId,proto3" json:"pokemon_id,omitempty"`               // PokeAPI のポケモンID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                           // ポケモン名
	Type1Id       int32                  `protobuf:"varint,3,opt,name=type1_id,json=type1Id,proto3" json:"type1_id,omitempty"`                     // タイプ1のID
	Type2Id       int32                  `protobuf:"varint,4,opt,name=type2_id,json=type2Id,proto3" json:"type2_id,omitempty"`                     // タイプ2のID（単タイプの場合は 0）
	BaseHp        int32                  `protobuf:"varint,5,opt,name=base_hp,json=baseHp,proto3" json:"base_hp,omitempty"`                        // 種族値 HP
	BaseAttack    int32                  `protobuf:"varint,6,opt,name=base_attack,json=baseAttack,proto3" json:"base_attack,omitempty"`            // 種族値 こうげき
	BaseDefense   int32                  `protobuf:"varint,7,opt,name=base_defense,json=baseDefense,proto3" json:"base_defense,omitempty"`         // 種族値 ぼうぎょ
	BaseSpAttack  int32                  `protobuf:"varint,8,opt,name=base_sp_attack,json=baseSpAttack,proto3" json:"base_sp_attack,omitempty"`    // 種族値 とくこう
	BaseSpDefense int32                  `protobuf:"varint,9,opt,name=base_sp_defense,json=baseSpDefense,proto3" json:"base_sp_defense,omitempty"` // 種族値 とくぼう
	BaseSpeed     int32                  `protobuf:"varint,10,opt,name=base_speed,json=baseSpeed,proto3" json:"base_speed,omitempty"`              // 種族値 すばやさ
	Abilities     []*AbilityInfo         `protobuf:"bytes,11,rep,name=abilities,proto3" json:"abilities,omitempty"`                                // 特性リスト（通常特性・夢特性を含む）
	WeightKg      float32                `protobuf:"fixed32,12,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`                // 体重(kg)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PokemonResponse) Reset() {
	*x = PokemonResponse{}
	mi := &file_dex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokemonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonResponse) ProtoMessage() {}

func (x *PokemonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonResponse.ProtoReflect.Descriptor instead.
func (*PokemonResponse) Descriptor() ([]byte, []int) {
	return file_dex_proto_rawDescGZIP(), []int{1}
}

func (x *PokemonResponse) GetPokemonId() int32 {
	if x != nil {
		return x.PokemonId
	}
	return 0
}

func (x *PokemonResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PokemonResponse) GetType1Id() int32 {
	if x != nil {
		return x.Type1Id
	}
	return 0
}

func (x *PokemonResponse) GetType2Id() int32 {
	if x != nil {
		return x.Type2Id
	}
	return 0
}

func (x *PokemonResponse) GetBaseHp() int32 {
	if x != nil {
		return x.BaseHp
	}
	return 0
}

func (x *PokemonResponse) GetBaseAttack() int32 {
	if x != nil {
		return x.BaseAttack
	}
	return 0
}

func (x *PokemonResponse) GetBaseDefense() int32 {
	if x != nil {
		return x.BaseDefense
	}
	return 0
}

func (x *PokemonResponse) GetBaseSpAttack() int32 {
	if x != nil {
		return x.BaseSpAttack
	}
	return 0
}

func (x *PokemonResponse) GetBaseSpDefense() int32 {
	if x != nil {
		return x.BaseSpDefense
	}
	return 0
}

func (x *PokemonResponse) GetBaseSpeed() int32 {
	if x != nil {
		return x.BaseSpeed
	}
	return 0
}

func (x *PokemonResponse) GetAbilities() []*AbilityInfo {
	if x != nil {
		return x.Abilities
	}
	return nil
}

func (x *PokemonResponse) GetWeightKg() float32 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

type AbilityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AbilityId     int32                  `protobuf:"varint,1,opt,name=ability_id,json=abilityId,proto3" json:"ability_id,omitempty"`      // PokeAPI の特性ID
	AbilityName   string                 `protobuf:"bytes,2,opt,name=ability_name,json=abilityName,proto3" json:"ability_name,omitempty"` // 特性名
	IsHidden      bool                   `protobuf:"varint,3,opt,name=is_hidden,json=isHidden,proto3" json:"is_hidden,omitempty"`         // true: 夢特性
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbilityInfo) Reset() {
	*x = AbilityInfo{}
	mi := &file_dex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbilityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbilityInfo) ProtoMessage() {}

func (x *AbilityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbilityInfo.ProtoReflect.Descriptor instead.
func (*AbilityInfo) Descriptor() ([]byte, []int) {
	return file_dex_proto_rawDescGZIP(), []int{2}
}

func (x *AbilityInfo) GetAbilityId() int32 {
	if x != nil {
		return x.AbilityId
	}
	return 0
}

func (x *AbilityInfo) GetAbilityName() string {
	if x != nil {
		return x.AbilityName
	}
	return ""
}

func (x *AbilityInfo) GetIsHidden() bool {
	if x != nil {
		return x.IsHidden
	}
	return false
}

// ── GetLearnableMoves ───────────────────────────────────────
type GetLearnableMovesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PokemonId     int32                  `protobuf:"varint,1,opt,name=pokemon_id,json=pokemonId,proto3" json:"pokemon_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLearnableMovesRequest) Reset() {
	*x = GetLearnableMovesRequest{}
	mi := &file_dex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLearnableMovesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLearnableMovesRequest) ProtoMessage() {}

func (x *GetLearnableMovesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLearnableMovesRequest.ProtoReflect.Descriptor instead.
func (*GetLearnableMovesRequest) Descriptor() ([]byte, []int) {
	return file_dex_proto_rawDescGZIP(), []int{3}
}

func (x *GetLearnableMovesRequest) GetPokemonId() int32 {
	if x != nil {
		return x.PokemonId
	}
	return 0
}

type LearnableMovesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moves         []*MoveResponse        `protobuf:"bytes,1,rep,name=moves,proto3" json:"moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LearnableMovesResponse) Reset() {
	*x = LearnableMovesResponse{}
	mi := &file_dex_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearnableMovesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearnableMovesResponse) ProtoMessage() {}

func (x *LearnableMovesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dex_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearnableMovesResponse.ProtoReflect.Descriptor instead.
func (*LearnableMovesResponse) Descriptor() ([]byte, []int) {
	return file_dex_proto_rawDescGZIP(), []int{4}
}

func (x *LearnableMovesResponse) GetMoves() []*MoveResponse {
	if x != nil {
		return x.Moves
	}
	return nil
}

// ── GetMove ────────────────────────────────────────────────
type GetMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MoveId        int32                  `protobuf:"varint,1,opt,name=move_id,json=moveId,proto3" json:"move_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMoveRequest) Reset() {
	*x = GetMoveRequest{}
	mi := &file_dex_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoveRequest) ProtoMessage() {}

func (x *GetMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dex_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoveRequest.ProtoReflect.Descriptor instead.
func (*GetMoveRequest) Descriptor() ([]byte, []int) {
	return file_dex_proto_rawDescGZIP(), []int{5}
}

func (x *GetMoveRequest) GetMoveId() int32 {
	if x != nil {
		return x.MoveId
	}
	return 0
}

type MoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MoveId        int32                  `protobuf:"varint,1,opt,name=move_id,json=moveId,proto3" json:"move_id,omitempty"`               // PokeAPI の技ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                  // 技名
	TypeId        int32                  `protobuf:"varint,3,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`               // タイプID
	DamageClass   string                 `protobuf:"bytes,4,opt,name=damage_class,json=damageClass,proto3" json:"damage_class,omitempty"` // 技の分類（physical / special / status）
	Power         int32                  `protobuf:"varint,5,opt,name=power,proto3" json:"power,omitempty"`                               // 威力（固定・変動ダメージ技の場合は 0）
	Accuracy      int32                  `protobuf:"varint,6,opt,name=accuracy,proto3" json:"accuracy,omitempty"`                         // 命中率（必中技の場合は 0）
	Pp            int32                  `protobuf:"varint,7,opt,name=pp,proto3" json:"pp,omitempty"`                                     // PP
	Priority      int32                  `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`                         // 優先度（-7〜+5）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	mi := &file_dex_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dex_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_dex_proto_rawDescGZIP(), []int{6}
}

func (x *MoveResponse) GetMoveId() int32 {
	if x != nil {
		return x.MoveId
	}
	return 0
}

func (x *MoveResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MoveResponse) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *MoveResponse) GetDamageClass() string {
	if x != nil {
		return x.DamageClass
	}
	return ""
}

func (x *MoveResponse) GetPower() int32 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *MoveResponse) GetAccuracy() int32 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *MoveResponse) GetPp() int32 {
	if x != nil {
		return x.Pp
	}
	return 0
}

func (x *MoveResponse) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// ── GetAbility ─────────────────────────────────────────────
type GetAbilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AbilityId     int32                  `protobuf:"varint,1,opt,name=ability_id,json=abilityId,proto3" json:"ability_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAbilityRequest) Reset() {
	*x = GetAbilityRequest{}
	mi := &file_dex_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAbilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAbilityRequest) ProtoMessage() {}

func (x *GetAbilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dex_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAbilityRequest.ProtoReflect.Descriptor instead.
func (*GetAbilityRequest) Descriptor() ([]byte, []int) {
	return file_dex_proto_rawDescGZIP(), []int{7}
}

func (x *GetAbilityRequest) GetAbilityId() int32 {
	if x != nil {
		return x.AbilityId
	}
	return 0
}

type AbilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AbilityId     int32                  `protobuf:"varint,1,opt,name=ability_id,json=abilityId,proto3" json:"ability_id,omitempty"`      // PokeAPI の特性ID
	AbilityName   string                 `protobuf:"bytes,2,opt,name=ability_name,json=abilityName,proto3" json:"ability_name,omitempty"` // 特性名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbilityResponse) Reset() {
	*x = AbilityResponse{}
	mi := &file_dex_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbilityResponse) ProtoMessage() {}

func (x *AbilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dex_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbilityResponse.ProtoReflect.Descriptor instead.
func (*AbilityResponse) Descriptor() ([]byte, []int) {
	return file_dex_proto_rawDescGZIP(), []int{8}
}

func (x *AbilityResponse) GetAbilityId() int32 {
	if x != nil {
		return x.AbilityId
	}
	return 0
}

func (x *AbilityResponse) GetAbilityName() string {
	if x != nil {
		return x.AbilityName
	}
	return ""
}

// ── GetItem ────────────────────────────────────────────────
type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_dex_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dex_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_dex_proto_rawDescGZIP(), []int{9}
}

func (x *GetItemRequest) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type ItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	FlavorText    string                 `protobuf:"bytes,4,opt,name=flavor_text,json=flavorText,proto3" json:"flavor_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemResponse) Reset() {
	*x = ItemResponse{}
	mi := &file_dex_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemResponse) ProtoMessage() {}

func (x *ItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dex_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemResponse.ProtoReflect.Descriptor instead.
func (*ItemResponse) Descriptor() ([]byte, []int) {
	return file_dex_proto_rawDescGZIP(), []int{10}
}

func (x *ItemResponse) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ItemResponse) GetFlavorText() string {
	if x != nil {
		return x.FlavorText
	}
	return ""
}

// ── GetPokemonList ─────────────────────────────────────────
type GetPokemonListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPokemonListRequest) Reset() {
	*x = GetPokemonListRequest{}
	mi := &file_dex_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPokemonListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPokemonListRequest) ProtoMessage() {}

func (x *GetPokemonListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dex_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPokemonListRequest.ProtoReflect.Descriptor instead.
func (*GetPokemonListRequest) Descriptor() ([]byte, []int) {
	return file_dex_proto_rawDescGZIP(), []int{11}
}

type PokemonListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pokemon       []*PokemonList         `protobuf:"bytes,1,rep,name=pokemon,proto3" json:"pokemon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PokemonListResponse) Reset() {
	*x = PokemonListResponse{}
	mi := &file_dex_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokemonListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonListResponse) ProtoMessage() {}

func (x *PokemonListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dex_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonListResponse.ProtoReflect.Descriptor instead.
func (*PokemonListResponse) Descriptor() ([]byte, []int) {
	return file_dex_proto_rawDescGZIP(), []int{12}
}

func (x *PokemonListResponse) GetPokemon() []*PokemonList {
	if x != nil {
		return x.Pokemon
	}
	return nil
}

type PokemonList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PokemonId     int32                  `protobuf:"varint,1,opt,name=pokemon_id,json=pokemonId,proto3" json:"pokemon_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PokemonList) Reset() {
	*x = PokemonList{}
	mi := &file_dex_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokemonList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonList) ProtoMessage() {}

func (x *PokemonList) ProtoReflect() protoreflect.Message {
	mi := &file_dex_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonList.ProtoReflect.Descriptor instead.
func (*PokemonList) Descriptor() ([]byte, []int) {
	return file_dex_proto_rawDescGZIP(), []int{13}
}

func (x *PokemonList) GetPokemonId() int32 {
	if x != nil {
		return x.PokemonId
	}
	return 0
}

func (x *PokemonList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_dex_proto protoreflect.FileDescriptor

const file_dex_proto_rawDesc = "" +
	"\n" +
	"\tdex.proto\x12\x03dex\"2\n" +
	"\x11GetPokemonRequest\x12\x1d\n" +
	"\n" +
	"pokemon_id\x18\x01 \x01(\x05R\tpokemonId\"\x91\x03\n" +
	"\x0fPokemonResponse\x12\x1d\n" +
	"\n" +
	"pokemon_id\x18\x01 \x01(\x05R\tpokemonId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\btype1_id\x18\x03 \x01(\x05R\atype1Id\x12\x19\n" +
	"\btype2_id\x18\x04 \x01(\x05R\atype2Id\x12\x17\n" +
	"\abase_hp\x18\x05 \x01(\x05R\x06baseHp\x12\x1f\n" +
	"\vbase_attack\x18\x06 \x01(\x05R\n" +
	"baseAttack\x12!\n" +
	"\fbase_defense\x18\a \x01(\x05R\vbaseDefense\x12$\n" +
	"\x0ebase_sp_attack\x18\b \x01(\x05R\fbaseSpAttack\x12&\n" +
	"\x0fbase_sp_defense\x18\t \x01(\x05R\rbaseSpDefense\x12\x1d\n" +
	"\n" +
	"base_speed\x18\n" +
	" \x01(\x05R\tbaseSpeed\x12.\n" +
	"\tabilities\x18\v \x03(\v2\x10.dex.AbilityInfoR\tabilities\x12\x1b\n" +
	"\tweight_kg\x18\f \x01(\x02R\bweightKg\"l\n" +
	"\vAbilityInfo\x12\x1d\n" +
	"\n" +
	"ability_id\x18\x01 \x01(\x05R\tabilityId\x12!\n" +
	"\fability_name\x18\x02 \x01(\tR\vabilityName\x12\x1b\n" +
	"\tis_hidden\x18\x03 \x01(\bR\bisHidden\"9\n" +
	"\x18GetLearnableMovesRequest\x12\x1d\n" +
	"\n" +
	"pokemon_id\x18\x01 \x01(\x05R\tpokemonId\"A\n" +
	"\x16LearnableMovesResponse\x12'\n" +
	"\x05moves\x18\x01 \x03(\v2\x11.dex.MoveResponseR\x05moves\")\n" +
	"\x0eGetMoveRequest\x12\x17\n" +
	"\amove_id\x18\x01 \x01(\x05R\x06moveId\"\xd5\x01\n" +
	"\fMoveResponse\x12\x17\n" +
	"\amove_id\x18\x01 \x01(\x05R\x06moveId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\atype_id\x18\x03 \x01(\x05R\x06typeId\x12!\n" +
	"\fdamage_class\x18\x04 \x01(\tR\vdamageClass\x12\x14\n" +
	"\x05power\x18\x05 \x01(\x05R\x05power\x12\x1a\n" +
	"\baccuracy\x18\x06 \x01(\x05R\baccuracy\x12\x0e\n" +
	"\x02pp\x18\a \x01(\x05R\x02pp\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x05R\bpriority\"2\n" +
	"\x11GetAbilityRequest\x12\x1d\n" +
	"\n" +
	"ability_id\x18\x01 \x01(\x05R\tabilityId\"S\n" +
	"\x0fAbilityResponse\x12\x1d\n" +
	"\n" +
	"ability_id\x18\x01 \x01(\x05R\tabilityId\x12!\n" +
	"\fability_name\x18\x02 \x01(\tR\vabilityName\")\n" +
	"\x0eGetItemRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\"x\n" +
	"\fItemResponse\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1f\n" +
	"\vflavor_text\x18\x04 \x01(\tR\n" +
	"flavorText\"\x17\n" +
	"\x15GetPokemonListRequest\"A\n" +
	"\x13PokemonListResponse\x12*\n" +
	"\apokemon\x18\x01 \x03(\v2\x10.dex.PokemonListR\apokemon\"@\n" +
	"\vPokemonList\x12\x1d\n" +
	"\n" +
	"pokemon_id\x18\x01 \x01(\x05R\tpokemonId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\x83\x03\n" +
	"\n" +
	"DexService\x12:\n" +
	"\n" +
	"GetPokemon\x12\x16.dex.GetPokemonRequest\x1a\x14.dex.PokemonResponse\x12O\n" +
	"\x11GetLearnableMoves\x12\x1d.dex.GetLearnableMovesRequest\x1a\x1b.dex.LearnableMovesResponse\x121\n" +
	"\aGetMove\x12\x13.dex.GetMoveRequest\x1a\x11.dex.MoveResponse\x12:\n" +
	"\n" +
	"GetAbility\x12\x16.dex.GetAbilityRequest\x1a\x14.dex.AbilityResponse\x121\n" +
	"\aGetItem\x12\x13.dex.GetItemRequest\x1a\x11.dex.ItemResponse\x12F\n" +
	"\x0eGetPokemonList\x12\x1a.dex.GetPokemonListRequest\x1a\x18.dex.PokemonListResponseB\x0fZ\rpob/dex/protob\x06proto3"

var (
	file_dex_proto_rawDescOnce sync.Once
	file_dex_proto_rawDescData []byte
)

func file_dex_proto_rawDescGZIP() []byte {
	file_dex_proto_rawDescOnce.Do(func() {
		file_dex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dex_proto_rawDesc), len(file_dex_proto_rawDesc)))
	})
	return file_dex_proto_rawDescData
}

var file_dex_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_dex_proto_goTypes = []any{
	(*GetPokemonRequest)(nil),        // 0: dex.GetPokemonRequest
	(*PokemonResponse)(nil),          // 1: dex.PokemonResponse
	(*AbilityInfo)(nil),              // 2: dex.AbilityInfo
	(*GetLearnableMovesRequest)(nil), // 3: dex.GetLearnableMovesRequest
	(*LearnableMovesResponse)(nil),   // 4: dex.LearnableMovesResponse
	(*GetMoveRequest)(nil),           // 5: dex.GetMoveRequest
	(*MoveResponse)(nil),             // 6: dex.MoveResponse
	(*GetAbilityRequest)(nil),        // 7: dex.GetAbilityRequest
	(*AbilityResponse)(nil),          // 8: dex.AbilityResponse
	(*GetItemRequest)(nil),           // 9: dex.GetItemRequest
	(*ItemResponse)(nil),             // 10: dex.ItemResponse
	(*GetPokemonListRequest)(nil),    // 11: dex.GetPokemonListRequest
	(*PokemonListResponse)(nil),      // 12: dex.PokemonListResponse
	(*PokemonList)(nil),              // 13: dex.PokemonList
}
var file_dex_proto_depIdxs = []int32{
	2,  // 0: dex.PokemonResponse.abilities:type_name -> dex.AbilityInfo
	6,  // 1: dex.LearnableMovesResponse.moves:type_name -> dex.MoveResponse
	13, // 2: dex.PokemonListResponse.pokemon:type_name -> dex.PokemonList
	0,  // 3: dex.DexService.GetPokemon:input_type -> dex.GetPokemonRequest
	3,  // 4: dex.DexService.GetLearnableMoves:input_type -> dex.GetLearnableMovesRequest
	5,  // 5: dex.DexService.GetMove:input_type -> dex.GetMoveRequest
	7,  // 6: dex.DexService.GetAbility:input_type -> dex.GetAbilityRequest
	9,  // 7: dex.DexService.GetItem:input_type -> dex.GetItemRequest
	11, // 8: dex.DexService.GetPokemonList:input_type -> dex.GetPokemonListRequest
	1,  // 9: dex.DexService.GetPokemon:output_type -> dex.PokemonResponse
	4,  // 10: dex.DexService.GetLearnableMoves:output_type -> dex.LearnableMovesResponse
	6,  // 11: dex.DexService.GetMove:output_type -> dex.MoveResponse
	8,  // 12: dex.DexService.GetAbility:output_type -> dex.AbilityResponse
	10, // 13: dex.DexService.GetItem:output_type -> dex.ItemResponse
	12, // 14: dex.DexService.GetPokemonList:output_type -> dex.PokemonListResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_dex_proto_init() }
func file_dex_proto_init() {
	if File_dex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dex_proto_rawDesc), len(file_dex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dex_proto_goTypes,
		DependencyIndexes: file_dex_proto_depIdxs,
		MessageInfos:      file_dex_proto_msgTypes,
	}.Build()
	File_dex_proto = out.File
	file_dex_proto_goTypes = nil
	file_dex_proto_depIdxs = nil
}
