// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"pob/box/internal/handler"
	"pob/box/internal/repository"
	"pob/box/internal/service"
	"pob/box/internal/shared"
	"pob/box/proto"
)

// Injectors from wire.go:

func NewContainer(db *shared.DBClient, dex proto.DexServiceClient) (*Container, error) {
	boxRepository := repository.NewBoxRepository(db)
	boxService := service.NewBoxService(boxRepository)
	boxPokemonRepository := repository.NewBoxPokemonRepository(db)
	boxPokemonService := service.NewBoxPokemonService(boxPokemonRepository, dex)
	boxHandler := handler.NewBoxHandler(boxService, boxPokemonService)
	partyRepository := repository.NewPartyRepository(db)
	partyService := service.NewPartyService(partyRepository)
	partyPokemonRepository := repository.NewPartyPokemonRepository(db)
	partyPokemonService := service.NewPartyPokemonService(partyPokemonRepository, boxPokemonRepository)
	partyHandler := handler.NewPartyHandler(partyService, partyPokemonService)
	dexHandler := handler.NewDexHandler(dex)
	grpcHandler := handler.NewGrpcHandler(partyPokemonService, boxPokemonService)
	container := &Container{
		Box:   boxHandler,
		Party: partyHandler,
		Dex:   dexHandler,
		Grpc:  grpcHandler,
	}
	return container, nil
}

// wire.go:

type Container struct {
	Box   *handler.BoxHandler
	Party *handler.PartyHandler
	Dex   *handler.DexHandler
	Grpc  *handler.GrpcHandler
}
